### Import Data & Inspect Structure

In [3]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [14]:
# Checking how the data is encoded to properly read it in the next step
import chardet

with open("GamingStudy_data.csv", "rb") as f:
    print(chardet.detect(f.read(10000)))

{'encoding': 'ISO-8859-1', 'confidence': 0.03321167337449891, 'language': 'en', 'mime_type': 'text/plain'}

In [33]:
df = pd.read_csv('GamingStudy_data.csv', encoding="ISO-8859-1")
df.head(3)

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S. No.           13464 non-null  int64
 1   Timestamp        13464 non-null  float64
 2   GAD1             13464 non-null  int64
 3   GAD2             13464 non-null  int64
 4   GAD3             13464 non-null  int64
 5   GAD4             13464 non-null  int64
 6   GAD5             13464 non-null  int64
 7   GAD6             13464 non-null  int64
 8   GAD7             13464 non-null  int64
 9   GADE             12815 non-null  str
 10  SWL1             13464 non-null  int64
 11  SWL2             13464 non-null  int64
 12  SWL3             13464 non-null  int64
 13  SWL4             13464 non-null  int64
 14  SWL5             13464 non-null  int64
 15  Game             13464 non-null  str
 16  Platform         13464 non-null  str
 17  Hours            13434 non-null  float64
 18  earnings         13464 non-null  str
 19  whyplay          13464 non-null  str
 20  League           11612 non-null  str
 21  highestleague    0 non-null      float64
 22  streams          13364 non-null  float64
 23  SPIN1            13340 non-null  float64
 24  SPIN2            13310 non-null  float64
 25  SPIN3            13324 non-null  float64
 26  SPIN4            13305 non-null  float64
 27  SPIN5            13298 non-null  float64
 28  SPIN6            13308 non-null  float64
 29  SPIN7            13326 non-null  float64
 30  SPIN8            13320 non-null  float64
 31  SPIN9            13306 non-null  float64
 32  SPIN10           13304 non-null  float64
 33  SPIN11           13277 non-null  float64
 34  SPIN12           13296 non-null  float64
 35  SPIN13           13277 non-null  float64
 36  SPIN14           13308 non-null  float64
 37  SPIN15           13317 non-null  float64
 38  SPIN16           13317 non-null  float64
 39  SPIN17           13289 non-null  float64
 40  Narcissism       13441 non-null  float64
 41  Gender           13464 non-null  str
 42  Age              13464 non-null  int64
 43  Work             13426 non-null  str
 44  Degree           11887 non-null  str
 45  Birthplace       13464 non-null  str
 46  Residence        13464 non-null  str
 47  Reference        13449 non-null  str
 48  Playstyle        13464 non-null  str
 49  accept           13050 non-null  str
 50  GAD_T            13464 non-null  int64
 51  SWL_T            13464 non-null  int64
 52  SPIN_T           12814 non-null  float64
 53  Residence_ISO3   13354 non-null  str
 54  Birthplace_ISO3  13343 non-null  str
dtypes: float64(23), int64(16), str(16)
memory usage: 5.6 MB

In [17]:
df.shape

(13464, 55)

### Explore individual columns

In [35]:
# .value_counts() for categorical variables

# ['Game', 'Platform', 'earnings', 'whyplay', 'League', 'Gender' 'Work', 'Degree', 'Birthplace', 'Residence', 'Reference', 'Playstyle']
# df.value_counts('Gender')

In [ ]:
# .describe() for numerical columns

df.describe()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,SWL1,SWL2,SWL3,SWL4,SWL5,Hours,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Age,GAD_T,SWL_T,SPIN_T
count,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.00000,13464.000000,13464.000000,13434.000000,0.0,13364.000000,13340.000000,13310.000000,13324.000000,13305.000000,13298.000000,13308.000000,13326.000000,13320.000000,13306.000000,13304.000000,13277.000000,13296.000000,13277.000000,13308.000000,13317.000000,13317.000000,13289.000000,13441.000000,13464.000000,13464.000000,13464.000000,12814.000000
mean,7096.839201,42054.841222,0.860963,0.673351,0.965761,0.724079,0.488042,0.911022,0.588755,3.720440,4.602050,4.34544,3.762032,3.358883,22.247357,NaN,11.233538,0.856897,1.210969,1.095392,1.682976,1.248985,1.348287,1.050503,1.405030,1.567338,0.917769,1.827446,0.892148,0.538827,1.252405,1.411054,0.620635,0.935962,2.027677,20.930407,5.211973,19.788844,19.848525
std,4114.478220,0.272948,0.926542,0.915724,0.982776,0.921971,0.837014,0.931168,0.894408,1.736264,1.696276,1.80943,1.818136,1.916319,70.284502,NaN,78.549209,0.907351,1.144054,1.164982,1.229730,1.221828,1.279251,1.221171,1.372777,1.383539,1.125849,1.488372,1.158235,0.944180,1.207463,1.349874,0.961853,1.180456,1.061842,3.300897,4.713267,7.229243,13.467493
min,1.000000,42052.004370,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.00000,1.000000,1.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,0.000000,5.000000,0.000000
25%,3532.750000,42054.716548,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000,3.00000,2.000000,2.000000,12.000000,NaN,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,2.000000,14.000000,9.000000
50%,7087.500000,42054.800675,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,4.000000,5.000000,5.00000,4.000000,3.000000,20.000000,NaN,8.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,20.000000,4.000000,20.000000,17.000000
75%,10654.250000,42054.932112,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,5.000000,6.000000,6.00000,5.000000,5.000000,28.000000,NaN,15.000000,1.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000,1.000000,3.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,3.000000,22.000000,8.000000,26.000000,28.000000
max,14250.000000,42058.363750,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,7.000000,7.000000,7.00000,7.000000,7.000000,8000.000000,NaN,9001.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,63.000000,21.000000,35.000000,68.000000