In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

## Inspect data

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31997 entries, 0 to 31996
Columns: 534 entries, URBRRL to POVRATTC_A
dtypes: float64(369), int64(164), str(1)
memory usage: 130.4 MB

In [ ]:
df = pd.read_csv('../data/adult19.csv')
df[[]].head()

,URBRRL,RATCAT_A,INCGRP_A,INCTCFLG_A,FAMINCTC_A,IMPINCFLG_A,PPSU,PSTRAT,HISPALLP_A,RACEALLP_A,DISAB3_A,SCHDYMSSTC_A,AFNOW,PHQCAT_A,YRSINUS_A,CITZNSTP_A,LEGMSTAT_A,MARSTAT_A,SASPPRACE_A,SASPPHISP_A,PRTNREDUC_A,SPOUSEDUC_A,PRTNRAGETC_A,SPOUSAGETC_A,PRTNRWKFT_A,PRTNRWRK_A,SPOUSWKFT_A,SPOUSWRK_A,SPOUSESEX_A,PRTNRSEX_A,SHTHPVAGEP_A,SHINGRXYRP_A,ZOSTAVXYRP_A,HHRESPSA_FLG,GADCAT_A,PCNTADTWFP_A,PCNTADTWKP_A,FDSCAT4_A,FDSCAT3_A,EMPDYSMSS2_A,EMPLSTWORK_A,EMPWRKFT_A,EMPWRKLSWK_A,EMPWKHRS2_A,DIFYRSTC_A,DIBAGETC_A,SMKECIGST_A,SMKCIGST_A,BMICAT_A,WEIGHTLBTC_A,HEIGHTTC_A,URGNT12MTC_A,EMERG12MTC_A,PSA5YRTC_A,PCNTTC,PCNT18UPTC,PCNTLT18TC,COVER65_A,COVER_A,EXCHANGE_A,NOTCOV_A,MILSPC1R_A,OGFLG_A,OPFLG_A,CHFLG_A,MAFLG_A,PLNWRKR2_A,PLNWRKR1_A,RSNHIMISS_A,RSNHIJOB_A,MCADVR_A,PRFLG_A,PLEXCHPR1_A,PRPREM1_A,PXCHNG1_A,HICOSTR2_A,HICOSTR1_A,OTHGOV_A,OTHPUB_A,IHS_A,MILITARY_A,CHIP_A,MEDICAID_A,MEDICARE_A,PRIVATE_A,PRPLCOV1_C_A,PRPLCOV2_C_A,PLEXCHOG_A,PLEXCHOP_A,EXCHPR2_A,EXCHPR1_A,EDUC_A,MAXEDUC_A,PARSTAT_A,SAPARENTSC_A,MLTFAMFLG_A,OVER65FLG_A,PCNTFAM_A,PCNTADLT_A,PCNTKIDS_A,NUMCAN_A,COLRCAGETC_A,HDNCKAGETC_A,OTHERAGETC_A,UTERUAGETC_A,THYROAGETC_A,THROAAGETC_A,STOMAAGETC_A,SKNDKAGETC_A,SKNNMAGETC_A,SKNMAGETC_A,RECTUAGETC_A,PROSTAGETC_A,PANCRAGETC_A,OVARYAGETC_A,MOUTHAGETC_A,MELANAGETC_A,LYMPHAGETC_A,LUNGAGETC_A,LIVERAGETC_A,LEUKEAGETC_A,LARYNAGETC_A,GALLBAGETC_A,ESOPHAGETC_A,COLONAGETC_A,CERVIAGETC_A,BREASAGETC_A,BRAINAGETC_A,BONEAGETC_A,BLOODAGETC_A,BLADDAGETC_A,OTHERCANP_A,COLRCCAN_A,HDNCKCAN_A,UTERUCAN_A,THYROCAN_A,THROACAN_A,STOMACAN_A,SKNDKCAN_A,SKNNMCAN_A,SKNMCAN_A,RECTUCAN_A,PROSTCAN_A,PANCRCAN_A,OVARYCAN_A,MOUTHCAN_A,MELANCAN_A,LYMPHCAN_A,LUNGCAN_A,LIVERCAN_A,LEUKECAN_A,LARYNCAN_A,GALLBCAN_A,ESOPHCAN_A,COLONCAN_A,CERVICAN_A,BREASCAN_A,BRAINCAN_A,BONECAN_A,BLOODCAN_A,BLADDCAN_A,HISDETP_A,HISP_A,REGION,SRVY_YR,SEX_A,AGEP_A,AGE65,ASTATNEW,HOUGVASST_A,HOUTENURE_A,HOUYRSLIV_A,FDSNEDAYS_A,FDSNOTEAT_A,FDSWEIGHT_A,FDSHUNGRY_A,FDSLESS_A,FDSSKIPDYS_A,FDSSKIP_A,FDSBALANCE_A,FDSLAST_A,FDSRUNOUT_A,FLUNCH12M_A,FWIC12M_A,FSNAP30D_A,FSNAP12M_A,INCOTHR_A,INCRETIRE_A,INCWELF_A,SSISSDIDSB_A,SSISSDIBTH_A,INCSSISSDI_A,INCSSRR_A,INCINTER_A,INCWRKO_A,EMPOFFHI_A,EMPPDSKLV_A,EMPRSNOWK_A,SCHCURENR_A,NATUSBORN_A,VACAREEV_A,VAHOSP_A,VADISB_A,COMBAT_A,AFVETTRN_A,AFVET_A,EVRMARRIED_A,SPOUSEP_A,SPOUSLIV_A,MARITAL_A,ORIENT_A,SMOKELSCUR_A,SMOKELSEV_A,PIPECUR_A,PIPEEV_A,CIGAR30D_A,CIGARCUR_A,CIGAREV_A,ECIGNOW_A,ECIGEV_A,CIG30D_A,SMK30D_A,CIGNOW_A,SMKNOW_A,SMKEV_A,ARTHPH_A,ARTHWT_A,ARTHWRK_A,ARTHLMT_A,JNTPN_A,JNTSYMP_A,PAITOOTH3M_A,PAIAPG3M_A,PAIHDFC3M_A,PAILLMB3M_A,PAIULMB3M_A,PAIBACK3M_A,PAINMEFF_A,PAIMOTHER_A,PAIMEDITAT_A,PAIMASSAGE_A,PAIYOGA_A,PAIGROUP_A,PAIPROGRAM_A,PAITALKTPY_A,PAICHIRO_A,PAIPHYSTPY_A,PAIAFFM3M_A,PAIWKLM3M_A,PAIAMNT_A,PAIFRQ3M_A,GAD77_A,GAD76_A,GAD75_A,GAD74_A,GAD73_A,GAD72_A,GAD71_A,PHQ88_A,PHQ87_A,PHQ86_A,PHQ85_A,PHQ84_A,PHQ83_A,PHQ82_A,PHQ81_A,MHTHND_A,MHTHDLY_A,MHTPYNOW_A,MHTHRPY_A,MHRX_A,DEPLEVEL_A,DEPMED_A,DEPFREQ_A,ANXLEVEL_A,ANXMED_A,ANXFREQ_A,HOMEHC12M_A,THERA12M_A,EYEEX12M_A,WRKHLTHFC_A,WORKHEALTH_A,SHTHPV_A,SHTTDAP_A,SHTTETANUS_A,TDAPPREG_A,SHINGWHEN_A,SHINGRIXNB_A,SHINGRIX_A,ZOSTAWHEN_A,ZOSTAVAX_A,SHTSHINGLE_A,SHTPNEUNB_A,SHTPNUEV_A,FLUPREG2_A,FLUPREG_A,SHTFLUY_A,SHTFLUM_A,SHTFLU12M_A,LIVEBIRTH_A,PREGFLUYR_A,BEXAMREAS_A,BEXAMWHEN_A,BREASTEXAM_A,MAMWHY1ST_A,MAMAGE1ST_A,MAMREASON_A,MAMWHEN_A,MAMEV_A,HYSTEV_A,CERVICNOT_A,CERVICRES_A,HPVTEST_A,PAPTEST_A,CERREASON_A,CERVICWHEN_A,CERVICEV_A,PSADISADV_A,PSAADVANT_A,PSASUGGEST_A,PSAREASON_A,PSAWHEN_A,PSATEST_A,COLKIND6_A,COLKIND5_A,COLKIND4_A,COLKIND3_A,COLKIND2_A,COLKIND1_A,COLPROBLEM_A,FITCOLG_A,COLOGUARD_A,FITHWHEN_A,FITHEV_A,CTCOLWHEN_A,CTCOLEV_A,COLOROTH_A,SIGWHEN_A,COLSIGWHEN_A,COLPAY_A,COLREASON_A,COLWHEN_A,COLORECTYP_A,COLORECTEV_A,DIABLAST_A,CHOLLAST_A,BPLAST_A,OPDFREQ_A,OPDCHRONIC_A,OPDACUTE_A,OPD3M_A,OPD12M_A,RXDG12M_A,RXDL12M_A,RXLS12M_A,RXSK12M_A,RX12M_A,MEDNG12M_A,MEDDL12M_A,HOSPONGT_A,USPLKIND_A,USUALPL_A,WELLVIS_A,WELLNESS_A,LASTDR_A,DENNG12M_A,DENDL12M_A,DENPREV_A,PAYWORRY_A,PAYNOBLLNW_A,PAYBLL12M_A,HINOTMYR_A,HINOTYR_A,RSNHIOTH_A,RSNHIWAIT_A,RSNHIMEET_A,RSNHICONF_A,RSNHIELIG_A,RSNHIWANT_A,RSNHICOST_A,HISTOPELIG_A,HISTOPCOST_A,HISTOPAGE_A,HISTOPMISS_A,HISTOPJOB_A,HILASTMY_A,HILAST_A,MILSPC3_A,MILSPC2_A,MILSPC1_A,OGHDHP_A,OGDEDUC_A,OGPREM_A,OGXCHNG_A,OPHDHP_A,OPDEDUC_A,OPPREM_A,OPXCHNG_A,CHHDHP_A,CHDEDUC_A,CHPREM_A,CHXCHNG_A,PRVSCOV2_A,PRVSCOV1_A,PRDNCOV2_A,PRDNCOV1_A,PRRXCOV2_A,PRRXCOV1_A,HSAHRA2_A,HSAHRA1_A,PRHDHP2_A,PRHDHP1_A,PRDEDUC2_A,PRDEDUC1_A,PLN2PAY6_A,PLN2PAY5_A,PLN2PAY4_A,PLN2PAY3_A,PLN2PAY2_A,PLN2PAY1_A,PLN1PAY6_A,PLN1PAY5_A,PLN1PAY4_A,PLN1PAY3_A,PLN1PAY2_A,PLN1PAY1_A,PLNEXCHG2_A,PLNEXCHG1_A,PRPOLH2_A,PRPOLH1_A,PRPLCOV2_A,PRPLCOV1_A,POLHLD2_A,POLHLD1_A,MAHDHP_A,MADEDUC_A,MAPREM_A,MAXCHNG_A,MCPARTD_A,MCHMO_A,MCCHOICE_A,MCPART_A,SINCOVRX_A,SINCOVVS_A,SINCOVDE_A,MCAIDPRB_A,MCAREPRB_A,HIKIND10_A,HIKIND09_A,HIKIND08_A,HIKIND07_A,HIKIND06_A,HIKIND05_A,HIKIND04_A,HIKIND03_A,HIKIND02_A,HIKIND01_A,HICOV_A,SOCWRKLIM_A,SOCSCLPAR_A,SOCERRNDS_A,UPPOBJCT_A,UPPRAISE_A,UPPSLFCR_A,COGAMTDFF_A,COGFRQDFF_A,COGTYPEDFF_A,COGMEMDFF_A,COMDIFF_A,EQSTEPS_A,EQWLK13M_A,EQWLK100_A,NOEQSTEPS_A,NOEQWLK13M_A,NOEQWLK100_A,PERASST_A,WCHAIR_A,CANEWLKR_A,STEPS_A,WLK13M_A,WLK100_A,EQUIP_A,DIFF_A,HEARINGDF_A,HEARAIDFR_A,HEARAID_A,VISIONDF_A,WEARGLSS_A,PREGNOW_A,DEPEV_A,ANXEV_A,DEMENEV_A,ARTHEV_A,COPDEV_A,DIBTYPE_A,DIBINSSTYR_A,DIBINSSTOP_A,DIBINSTIME_A,DIBINS_A,DIBPILL_A,DIBEV_A,GESDIB_A,PREDIB_A,CANEV_A,ASER12M_A,ASAT12M_A,ASTILL_A,ASEV_A,ASPONOWN_A,ASPMEDSTP_A,ASPMEDNOWN_A,ASPMEDEV_A,STREV_A,MIEV_A,ANGEV_A,CHDEV_A,CHLMED_A,CHL12M_A,CHLEV_A,HYPMED_A,HYP12M_A,HYPDIF_A,HYPEV_A,PHSTAT_A,PROXYREL_A,PROXY_A,AVAIL_A,HHSTAT_A,INTV_QRT,RECTYPE,WTFA_A,WTIA_A,HHX,POVRATTC_A
0,4,9,3,0,60000,2,2,122,3,2,2,NaN,2.0,1,NaN,1,3,1,2.0,1.0,NaN,8.0,NaN,97.0,NaN,NaN,NaN,8.0,2.0,NaN,NaN,NaN,NaN,1.0,1,0,0,1,1,NaN,2.0,NaN,2,NaN,NaN,NaN,3,4,3,201,71,0,0,NaN,3,2,1,NaN,3.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,1,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,7,8.0,1,3,2,0,3,2,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,3,2019,1,97,1.0,1,NaN,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1,1,NaN,NaN,3.0,2,1,2.0,2.0,2.0,1.0,2.0,1,NaN,NaN,1.0,1,2,NaN,2,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,NaN,2,2.0,NaN,2,5,NaN,2,5,2,2,2,2.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,2.0,2,2.0,2.0,2.0,1,2,2,2,1.0,1,NaN,1.0,1,2,2,1,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,NaN,NaN,2,2,2,2,1,2,2,2,2,2,1,2,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1,NaN,2,1,1,NaN,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,2,2,2,2.0,2.0,1,NaN,NaN,NaN,2,3,NaN,NaN,1,1,1,10,13177.008,7601.336,H048109,2.96
1,4,9,3,0,50000,0,2,122,2,1,2,NaN,1.0,1,NaN,1,3,1,1.0,1.0,NaN,6.0,NaN,28.0,NaN,NaN,1.0,1.0,1.0,NaN,18.0,NaN,NaN,1.0,1,2,2,1,1,0.0,NaN,1.0,1,35.0,NaN,NaN,1,2,2,130,62,0,0,NaN,2,2,0,NaN,3.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,1,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,6,6.0,3,3,2,0,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,3,2019,2,28,NaN,1,2.0,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,2.0,NaN,2,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,2.0,2.0,NaN,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,1.0,1,2,NaN,2,3.0,1,NaN,NaN,2,2.0,1,3.0,15.0,NaN,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,2,1,1,2,1,1,1,2,1,1,1,1,1,1,2,2,NaN,2,2.0,NaN,2,5,3.0,2,4,2,2,1,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,2,2,2,1.0,1,NaN,1.0,1,2,2,1,2,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,2,2,2,2,1,2,2,2,2,2,1,2,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1,NaN,2,1,2,2.0,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,2,2,2,2,NaN,NaN,2,NaN,NaN,NaN,2,1,NaN,NaN,1,1,1,10,6140.552,3344.434,H027044,2.97
2,4,12,3,0,65000,1,2,122,2,1,2,NaN,NaN,1,NaN,1,3,1,1.0,1.0,NaN,4.0,NaN,67.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,2016.0,NaN,1,0,1,8,8,NaN,3.0,NaN,2,NaN,NaN,NaN,3,4,3,215,74,0,0,5.0,2,2,0,4.0,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,3,3,3,1,3,NaN,NaN,NaN,NaN,NaN,NaN,5,5.0,3,3,2,1,2,2,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,3,2,3,2019,1,72,NaN,1,NaN,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,7,7,NaN,NaN,NaN,7,7.0,7.0,7.0,NaN,NaN,7.0,7.0,7,1,NaN,NaN,3.0,2,1,2.0,2.0,2.0,1.0,2.0,1,NaN,NaN,1.0,1,2,NaN,2,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,2,1.0,2.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,2,NaN,2,2.0,1.0,2,4,1.0,2,4,2,2,1,2.0,2.0,NaN,9.0,1.0,NaN,NaN,NaN,2.0,NaN,1.0,1.0,1.0,1,NaN,NaN,2018.0,10.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,2.0,1.0,1.0,1,1,1,NaN,NaN,NaN,NaN,2.0,2,2.0,2.0,2.0,1,2,2,2,1.0,1,NaN,1.0,1,2,2,1,2,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,3.0,1,2,1,NaN,NaN,2,2,2,2,2,2,2,2,1,2,1,2,1,1,1,1,1,1.0,1.0,1.0,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1,3.0,1,1,1,NaN,2,2,2,1,2,NaN,NaN,NaN,NaN,2.0,1.0,2,NaN,1,1,NaN,NaN,NaN,2,2.0,NaN,NaN,2.0,2,2,2,2,1.0,1.0,1,1.0,1.0,1.0,1,3,NaN,NaN,1,1,1,10,9191.061,6949.498,H058855,4.28
3,4,14,5,0,120000,0,2,122,1,8,2,NaN,2.0,1,NaN,1,3,1,2.0,2.0,NaN,5.0,NaN,60.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,1,1,2,1,1,0.0,NaN,1.0,1,40.0,NaN,NaN,3,4,4,290,72,0,0,5.0,2,2,0,NaN,3.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,1,3,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,7,7.0,3,3,2,0,2,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,3,2019,1,60,NaN,1,NaN,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,3,NaN,NaN,NaN,2,1.0,1.0,2.0,NaN,NaN,2.0,2.0,1,1,1.0,1.0,NaN,2,1,2.0,2.0,1.0,2.0,2.0,1,NaN,NaN,1.0,1,2,NaN,2,NaN,2,NaN,NaN,2,NaN,2,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,2,NaN,2,2.0,1.0,2,4,NaN,2,5,2,2,1,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,1,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,2.0,1.0,1.0,1,1,1,NaN,NaN,NaN,NaN,2.0,2,2.0,2.0,2.0,1,2,2,2,1.0,1,NaN,1.0,1,2,2,1,3,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,1,NaN,NaN,2,2,2,2,1,2,2,2,2,2,1,2,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,1,1,NaN,2,2,2,NaN,2,2,2,1,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,NaN,NaN,NaN,2,2.0,NaN,NaN,2.0,2,2,2,2,NaN,NaN,2,1.0,1.0,1.0,1,2,NaN,NaN,1,1,1,10,7900.035,6446.327,H031993,7.13
4,1,4,1,0,30000,0,2,115,2,1,2,NaN,2.0,3,NaN,1,3,1,1.0,1.0,NaN,5.0,NaN,58.0,NaN,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2,1,2,3,2,0.0,8.0,8.0,1,98.0,2.0,58.0,3,1,4,290,72,5,1,NaN,4,3,1,NaN,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,2,3,3,1,3,3,NaN,NaN,NaN,NaN,NaN,NaN,5,5.0,1,1,2,0,4,3,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,3,2019,1,60,NaN,1,NaN,1,5,NaN,2.0,2.0,2.0,1.0,7.0,1.0,3,2,2,2.0,2.0,1.0,1,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2,1,2.0,2.0,2.0,2,1,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,1.0,1,2,NaN,2,3.0,1,0.0,3.0,1,NaN,2,NaN,NaN,15.0,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,1.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2,1,1,2,2,2,3,1,4,2,2,3,2,3,4,1,1,1.0,1,NaN,3.0,1,1,3.0,1,2,2,2,2,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1,NaN,NaN,2018.0,9.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,NaN,2.0,1.0,6.0,3.0,1.0,1,1,1,NaN,NaN,NaN,NaN,2.0,2,1.0,2.0,2.0,1,1,1,2,5.0,1,3.0,2.0,1,1,1,6,1,1.0,1,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2,2,2,NaN,NaN,2,2,2,2,2,2,1,2,2,2,1,1,1,1,1,1,1,1.0,2.0,3.0,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2,2,1,NaN,2,1,1,NaN,1,1,2,2,1,2.0,NaN,NaN,NaN,2.0,1.0,1,NaN,1,2,2.0,1.0,1.0,1,NaN,NaN,1.0,1.0,2,1,1,1,1.0,2.0,1,1.0,1.0,1.0,1,4,NaN,NaN,1,1,1,10,10875.772,8646.586,H007122,1.13

In [26]:
# Confirm this column can be used for key
# Number matches entry numbers from .info()
df['HHX'].nunique()

31997

## Pull columns relevant to analysis

In [ ]:
# GADCAT_A breaks the totals into categories; page 416 of codebook

working_df = df[['HHX', 'SEX_A', 'AGEP_A', 'EMPWRKFT_A', 'EDUC_A', 'GAD71_A', 'GAD72_A', 'GAD73_A', 'GAD74_A', 'GAD75_A', 'GAD76_A', 'GAD77_A', 'GADCAT_A']]

working_df.head()

,HHX,SEX_A,AGEP_A,EMPWRKFT_A,EDUC_A,GAD71_A,GAD72_A,GAD73_A,GAD74_A,GAD75_A,GAD76_A,GAD77_A,GADCAT_A
0,H048109,1,97,NaN,7,1,1,1,1,1,1,1,1
1,H027044,2,28,1.0,6,1,1,2,1,1,2,2,1
2,H058855,1,72,NaN,5,1,1,1,1,1,1,1,1
3,H031993,1,60,1.0,7,1,1,1,1,1,1,1,1
4,H007122,1,60,8.0,5,3,2,2,2,1,1,2,2